---
# tasks file for setup_node_exporter
- name: Configure the node exporter
  import_tasks: playbook_for_install_node.yaml

- name: Configure UFW for node exporter
  import_tasks: playbook_for_ufw_configuration.yaml