global:
  resolve_timeout: 5m
  smtp_smarthost: "smtp.gmail.com:587"
  smtp_from: "alerts@example.com"
  smtp_auth_username: "alerts@example.com"
  smtp_auth_password: "EMAIL_PASSWORD"
  smtp_require_tls: true

route:
  receiver: "email-alerts"
  group_by: ["alertname", "job"]
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h

receivers:
  - name: "email-alerts"
    email_configs:
      - to: "oncall@example.com"

