global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "172.16.7.130:9093"

scrape_configs:
  # Prometheus self-monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Example: Node Exporter
  # - job_name: "node_exporter"
  #   static_configs:
  #     - targets: ["node-exporter:9100"]
  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "172.16.7.131:9100"
  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "172.16.7.131:8080"
  - job_name: "nginx-exporter"
    static_configs:
      - targets:
          - "172.16.7.131:9113"
  - job_name: "redis_exporter"
    static_configs:
      - targets:
          - "172.16.7.131:9121"
