---
- name: Download the TAR file for system exporter on client VM
  get_url:
    url: https://github.com/prometheus-community/systemd_exporter/releases/download/v0.6.0/systemd_exporter-0.6.0.linux-amd64.tar.gz
    dest: /tmp/systemd_exporter.tar.gz
    mode: '0644'

- name: Create the systemd_exporter user with no bash
  ansible.builtin.user:
    name: systemd_exporter
    shell: /sbin/nologin
    system: yes
    create_home: no

- name: Extract the node_exporter tar file
  ansible.builtin.unarchive:
    src: /tmp/systemd_exporter.tar.gz
    dest: /usr/local/bin/
    remote_src: yes
    owner: systemd_exporter
    group: systemd_exporter
    mode: '0755'

- name: Create the daemon file for systemd_exporter
  ansible.builtin.copy:
    src: ../files/systemd_exporter.service
    dest: /etc/systemd/system/systemd_exporter.service
    mode: '0644'
  notify:
    - Restart the systemd_exporter service

- name: Start and enable the systemd_exporter service
  ansible.builtin.systemd:
    name: systemd_exporter
    state: restarted
    enabled: yes
    daemon_reload: yes
