---
- name: Allow SSH port of UFW
  ufw:
    rule: allow
    port: 22
    proto: tcp
    state: enabled
    comment: "Allow SSH connections"
  notify:
    - Restart the UFW services

- name: Allow systemd_exporter port through the UFW
  ufw:
    rule: allow
    port: 9558
    proto: tcp
    state: enabled
    comment: "Allow systemd_exporter metrics port"
  notify:
    - Restart the UFW services