---
- name: Introducing the playbook for installing and configuring node exporter
  hosts: exporter
  become: yes
  gather_facts: yes
  roles:

    #- role: Create_required_users
    - role: setup_redis_exporter
      # when: ansible_facts['os_family'] == "Ubuntu"
